name: Python application

on: [push]

env:
  MY_NAME: DZA-build
  PY_DOCKER_CONTAINER_NAME: aeggrid
  PROJECT_PATH: /_work/pyaction/pyaction

jobs:

    prebuild:

    runs-on: [self-hosted, linux]

    steps:
        - name: Show technical info
          env:
            MY_VAR: sample value
          run: |
            echo $MY_VAR
            echo $SECRET_USER_NAME
            docker --version

    build:

    runs-on: [self-hosted, linux]

    steps:
        - name: Checkout source code (GitHub action)
          if: ${{ 1==2 }}
          uses: actions/checkout@v2

        - name: Build Docker image
          run: |
            cd $PROJECT_PATH
            ls -la
            docker build -t $PY_DOCKER_CONTAINER_NAME .
