name: Python application

on: [push]

env:
  MY_NAME: DZA-build
  PY_DOCKER_CONTAINER_NAME: aeggrid

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
      run: |
        echo $MY_VAR $MY_NAME
        docker --version    

    - name: Build Docker image
      run: |
        apt -y install tree
        pwd
        ls -la
        tree -d /_work
        docker build -t $PY_DOCKER_CONTAINER_NAME .