name: Python application

on: [push]

env:
  MY_NAME: DZA-build
  PY_DOCKER_CONTAINER_NAME: aeggrid
  PROJECT_PATH: /_work/pyaction/pyaction
  SECRET_USER_NAME: ${{ secrets.SECRET_USER_NAME }}
  SECRET_SWITCH: ${{ secrets.SECRET_SWITCH }}

jobs:
    prepare_all:
        name: Initial operations
        runs-on: [self-hosted, linux]
        steps:
        - name: Show technical info
          env:
            MY_VAR: sample value
          run: |
            echo $MY_VAR
            echo $SECRET_USER_NAME
            docker --version
        - name: IF statement based on secret
          if: env.SECRET_SWITCH=='should be visible'
          run: |
            echo "Secrets are visible to the pipeline. OK."

    build:
        name: Build code
        runs-on: [self-hosted, linux]
        steps:
            - name: Checkout source code (GitHub action)
              uses: actions/checkout@v2
            - name: Set up Python 3.6
              run: |
                apt-get -y install python3
            - name: Install dependencies
              run: |
                python3 -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Lint with flake8
              run: |
                pip install flake8
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Build Docker image
              run: |
                cd $PROJECT_PATH
                ls -la
                docker build -t $PY_DOCKER_CONTAINER_NAME .

    job_1:
      name: Add 3 and 7
      runs-on: [self-hosted, linux]
      steps:
        - shell: bash
          run: |
            expr 3 + 7 > test-artf.txt
        - name: Upload math result for job 1
          uses: actions/upload-artifact@v1
          with:
            name: test-artf
            path: test-artf.txt



