name: Python application

on: [push]

env:
  MY_NAME: DZA-build
  PY_DOCKER_CONTAINER_NAME: aeggrid
  PROJECT_PATH: /_work/pyaction/pyaction
  SECRET_USER_NAME: ${{ secrets.SECRET_USER_NAME }}

jobs:
    prepare_all:
        name: Initial operations
        runs-on: [self-hosted, linux]
        steps:
        - name: Show technical info
          env:
            MY_VAR: sample value
          run: |
            echo $MY_VAR
            echo $SECRET_USER_NAME
            docker --version
        - name: IF statement based on secret
          if: $SECRET_USER_NAME=='1'
          run: |
            echo "ENTERED!"
