name: Python application

on: [push]

env:
  MY_NAME: DZA-build

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
      run: |
        echo $MY_NAME $MY_VAR.